/**
 * ViroARRitualOverlay — Death-Stranding-style ritual circle AR rendering.
 *
 * Independent from ViroAROverlay (the production v122 sphere/icon renderer).
 * Both files share the SAME GPS anchoring + ARKit tracking primitives but
 * differ in visual presentation:
 *   - ViroAROverlay     → 3D sphere with PBR icon geometry (current production)
 *   - ViroARRitualOverlay → ground-plane ritual circle + chiral strands +
 *                           distance-triggered debris (this file, experimental)
 *
 * Toggle between them via ARScreen mode switch. This file does NOT modify
 * any production rendering; if abandoned, simply delete and remove the
 * import from ARScreen.
 *
 * Milestone 1: ground ritual circle only (no strands, no debris yet).
 */
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import {
  ViroARScene,
  ViroARSceneNavigator,
  ViroQuad,
  ViroNode,
  ViroAmbientLight,
  ViroDirectionalLight,
  ViroMaterials,
  ViroAnimations,
  ViroTrackingStateConstants,
  type ViroTrackingState,
  type ViroTrackingReason,
} from '@reactvision/react-viro';
import type { Marker } from '../store/useMarkerStore';
import { useMarkerStore } from '../store/useMarkerStore';
import { crashLogger } from '../services/crashLogger';

// ── Type → ritual circle texture mapping ──────────────────────
// Each PNG is a 1024×1024 transparent ring with type-coloured runes +
// centre icon. Generated by app/scripts/gen_ritual_circles.mjs.
const RITUAL_TEX = {
  danger:   require('../../assets/ar/ritual_circle_danger.png'),
  supply:   require('../../assets/ar/ritual_circle_supply.png'),
  junction: require('../../assets/ar/ritual_circle_junction.png'),
  scenic:   require('../../assets/ar/ritual_circle_scenic.png'),
  cairn:    require('../../assets/ar/ritual_circle_cairn.png'),
} as const;

// Type aliases — same normalisation as ViroAROverlay so old DB rows keep working
const TYPE_REMAP: Record<string, keyof typeof RITUAL_TEX> = {
  water: 'supply',
  free:  'cairn',
  hut:   'cairn',
};
function normalizeType(t: string): keyof typeof RITUAL_TEX {
  if (t in RITUAL_TEX) return t as keyof typeof RITUAL_TEX;
  return TYPE_REMAP[t] ?? 'cairn';
}

// ── Constants ──────────────────────────────────────────────────
// Eye-level offset: place ritual centre slightly below ARKit camera Y so
// user looks down at it (same logic as ViroAROverlay v68 — GPS altitude is
// unreliable, anchor relative to camera height instead).
const RITUAL_GROUND_OFFSET_M = -1.2;
// Visibility range — beyond this, ritual circle is hidden (edge arrows
// take over, same threshold as production overlay).
const VISIBLE_RANGE_M = 50;
const NEAR_THRESHOLD_M = 10;
// Ritual circle physical size. 2m diameter = readable at 5–20m.
const RITUAL_BASE_SIZE_M = 2.0;
// Stable tracking settle window (ms). ARKit briefly reports TRACKING_NORMAL
// during relocalisation while the world transform is still being corrected.
const TRACKING_SETTLE_MS = 1500;

// ── GPS → ARKit world coords ──────────────────────────────────
// Identical math to ViroAROverlay.gpsToArWorld but inlined to keep this
// file self-contained.
function gpsToArWorld(
  origin: { lat: number; lng: number; alt?: number | null },
  target: { lat: number; lng: number; alt?: number | null },
): [number, number, number] {
  const dLat = target.lat - origin.lat;
  const dLng = target.lng - origin.lng;
  const cosLat = Math.cos((origin.lat * Math.PI) / 180);
  const northM = dLat * 111000;
  const eastM = dLng * 111000 * cosLat;
  return [eastM, RITUAL_GROUND_OFFSET_M, -northM];
}

interface CairnWorldPos {
  id: string;
  type: string;
  x: number; y: number; z: number;
  dist: number;
}

interface Props {
  markers: Marker[];
  userPos: { lat: number; lng: number; alt?: number | null } | null;
  userHeading: number | null;
  onStatus?: (status: { glReady: boolean; cairnCount: number }) => void;
  onCairnPress?: (markerId: string) => void;
}

// ─────────────────────────────────────────────────────────────────
// AR scene (inner — accesses viroAppProps via polling, same pattern as
// ViroAROverlay because viroAppProps is mutated in-place not via React state).
// ─────────────────────────────────────────────────────────────────
function RitualARScene(props: any) {
  const [liveProps, setLiveProps] = useState<{
    arkitOrigin: { lat: number; lng: number; alt?: number | null } | null;
    markers: Marker[];
    onCairnPress?: (id: string) => void;
  }>(() => {
    const p = props.sceneNavigator?.viroAppProps ?? {};
    return {
      arkitOrigin: p.arkitOrigin ?? null,
      markers: p.markers ?? [],
      onCairnPress: p.onCairnPress,
    };
  });

  useEffect(() => {
    const id = setInterval(() => {
      const p = props.sceneNavigator?.viroAppProps ?? {};
      setLiveProps(prev => {
        const nextMarkers: Marker[] = p.markers ?? [];
        if (
          prev.arkitOrigin === p.arkitOrigin &&
          prev.markers.length === nextMarkers.length &&
          prev.onCairnPress === p.onCairnPress
        ) return prev;
        return {
          arkitOrigin: p.arkitOrigin ?? null,
          markers: nextMarkers,
          onCairnPress: p.onCairnPress,
        };
      });
    }, 500);
    return () => clearInterval(id);
  }, []);

  const { arkitOrigin, markers, onCairnPress } = liveProps;
  const [tracking, setTracking] = useState(false);
  const [stableTracking, setStableTracking] = useState(false);
  const [materialsReady, setMaterialsReady] = useState(false);

  // ── Register materials + animations (deferred to mount, RN-safe) ──
  useEffect(() => {
    try {
      const types = ['danger', 'supply', 'junction', 'scenic', 'cairn'] as const;
      const mats: Record<string, any> = {};
      for (const t of types) {
        // Constant lighting + Add blend = ground glyph self-illuminated,
        // plays well in low light AND survives bright overcast (the PNG
        // already has high contrast). diffuseTexture references the
        // pre-rendered ritual ring asset.
        mats[`ritual${t}`] = {
          lightingModel: 'Constant',
          diffuseTexture: RITUAL_TEX[t],
          blendMode: 'Add',
          writesToDepthBuffer: false,
          readsFromDepthBuffer: true,
        };
      }
      ViroMaterials.createMaterials(mats);

      // Animations: slow rotation around Y (the quad is rotated -90° on X
      // so it lies flat on ground; rotateY animates around its centre axis).
      // Single non-chained animation only — chained animations were a known
      // source of accumulating-state bugs in production AR (see v82-v83 in
      // ViroAROverlay history). One animation, looped, no chain.
      ViroAnimations.registerAnimations({
        ringSpinSlow: {
          properties: { rotateY: '+=360' },
          duration: 60000,           // 60s/rev — barely perceptible, just alive
          easing: 'Linear',
        },
      });

      setMaterialsReady(true);
      crashLogger.breadcrumb('ritualAR:materials-registered');
    } catch (e: any) {
      crashLogger.breadcrumb(`ritualAR:material-error ${e?.message ?? e}`);
    }
  }, []);

  // ── Tracking state ─────────────────────────────────────────────
  const onTrackingUpdated = useCallback((state: ViroTrackingState, _reason: ViroTrackingReason) => {
    const ok = state === ViroTrackingStateConstants.TRACKING_NORMAL;
    setTracking(ok);
    crashLogger.breadcrumb(`ritualAR:tracking state=${state}`);
  }, []);

  useEffect(() => {
    if (!tracking) {
      setStableTracking(false);
      return;
    }
    const id = setTimeout(() => setStableTracking(true), TRACKING_SETTLE_MS);
    return () => clearTimeout(id);
  }, [tracking]);

  // ── World position computation ────────────────────────────────
  const cairnNodes = useMemo<CairnWorldPos[]>(() => {
    if (!arkitOrigin) return [];
    const out: CairnWorldPos[] = [];
    for (const m of markers) {
      const [x, y, z] = gpsToArWorld(arkitOrigin, m as any);
      const dLat = ((m as any).lat - arkitOrigin.lat) * 111000;
      const cosLat = Math.cos((arkitOrigin.lat * Math.PI) / 180);
      const dLng = ((m as any).lng - arkitOrigin.lng) * 111000 * cosLat;
      const dist = Math.sqrt(dLat * dLat + dLng * dLng);
      if (dist > VISIBLE_RANGE_M) continue;
      out.push({ id: m.id, type: m.type as string, x, y, z, dist });
    }
    return out;
  }, [arkitOrigin, markers]);

  return (
    <ViroARScene onTrackingUpdated={onTrackingUpdated}>
      {/* Soft ambient + warm directional — keeps PNG colours readable
          regardless of real-world lighting. Constant material does NOT
          react to lights but other future layers (text labels) might. */}
      <ViroAmbientLight color="#ffffff" intensity={300} />
      <ViroDirectionalLight color="#ffffff" direction={[0.0, -1.0, -0.5]} intensity={500} />

      {materialsReady && stableTracking && cairnNodes.map((c) => (
        <RitualInstance
          key={c.id}
          id={c.id}
          type={c.type}
          x={c.x}
          y={c.y}
          z={c.z}
          dist={c.dist}
          onPress={onCairnPress}
        />
      ))}
    </ViroARScene>
  );
}

// ─────────────────────────────────────────────────────────────────
// RitualInstance — one marker rendered as ground ritual circle.
// M1 scope: just the circle. Strands + label + debris will be added
// in M2/M3/M4.
// ─────────────────────────────────────────────────────────────────
function RitualInstance(props: {
  id: string;
  type: string;
  x: number; y: number; z: number;
  dist: number;
  onPress?: (id: string) => void;
}) {
  const { id, type, x, y, z, dist, onPress } = props;
  const normalized = normalizeType(type);
  const matName = `ritual${normalized}`;

  // Distance-aware scale: at 0–10m show natural size, fade larger toward
  // 50m so it remains visible from afar without being huge up close.
  let sizeMul: number;
  if (dist <= NEAR_THRESHOLD_M) {
    sizeMul = 1.0;
  } else {
    const t = Math.min(1, (dist - NEAR_THRESHOLD_M) / (VISIBLE_RANGE_M - NEAR_THRESHOLD_M));
    sizeMul = 1.0 + t * 1.5;     // grows to 2.5x at edge of visibility
  }
  const size = RITUAL_BASE_SIZE_M * sizeMul;

  const onPressCb = useCallback(() => {
    crashLogger.breadcrumb(`ritualAR:press id=${id.slice(-6)}`);
    onPress?.(id);
  }, [id, onPress]);

  useEffect(() => {
    crashLogger.breadcrumb(
      `ritualAR:render id=${id.slice(-6)} type=${type} norm=${normalized} dist=${dist.toFixed(1)} size=${size.toFixed(2)}`,
    );
  }, [id, type, normalized, dist, size]);

  return (
    <ViroNode position={[x, y, z]} onClick={onPressCb}>
      {/* Outer wrapper handles the slow rotation. Inner quad lies flat on
          the ground (rotation X = -90°). The quad uses Add blend so the
          ring glows additively on top of the camera feed. */}
      <ViroNode
        animation={{ name: 'ringSpinSlow', run: true, loop: true }}
      >
        <ViroQuad
          rotation={[-90, 0, 0]}                // lay flat on ground
          width={size}
          height={size}
          materials={[matName]}
        />
      </ViroNode>
    </ViroNode>
  );
}

// ─────────────────────────────────────────────────────────────────
// Public component — same Props shape as ViroAROverlay so ARScreen
// can swap them with a single ternary.
// ─────────────────────────────────────────────────────────────────
export function ViroARRitualOverlay({
  markers,
  userPos,
  userHeading: _userHeading,
  onStatus,
  onCairnPress,
}: Props) {
  const arkitOriginRef = useRef<{ lat: number; lng: number; alt?: number | null } | null>(null);
  const [originReady, setOriginReady] = useState(false);

  // Reuse the SAME persisted origin as ViroAROverlay so switching modes
  // doesn't move the markers (both renderers share the world frame).
  const persistedArOrigin = useMarkerStore(s => s.arOrigin);
  const setArOriginIfMissing = useMarkerStore(s => s.setArOriginIfMissing);

  useEffect(() => {
    if (persistedArOrigin) {
      arkitOriginRef.current = { ...persistedArOrigin };
      setOriginReady(true);
      crashLogger.breadcrumb(
        `ritualAR:origin-restored lat=${persistedArOrigin.lat.toFixed(6)} lng=${persistedArOrigin.lng.toFixed(6)}`,
      );
    } else {
      arkitOriginRef.current = null;
      setOriginReady(false);
      crashLogger.breadcrumb('ritualAR:origin-reset');
    }
    return () => { crashLogger.breadcrumb('ritualAR:session-ended'); };
  }, []);

  useEffect(() => {
    if (!arkitOriginRef.current && userPos) {
      const o = { lat: userPos.lat, lng: userPos.lng, alt: userPos.alt ?? null };
      arkitOriginRef.current = o;
      setOriginReady(true);
      setArOriginIfMissing(o);
      crashLogger.breadcrumb(
        `ritualAR:origin-set lat=${userPos.lat.toFixed(6)} lng=${userPos.lng.toFixed(6)}`,
      );
    }
  }, [userPos?.lat, userPos?.lng, userPos?.alt]);

  useEffect(() => {
    if (onStatus) onStatus({ glReady: originReady, cairnCount: markers.length });
  }, [markers.length, onStatus, originReady]);

  useEffect(() => {
    crashLogger.breadcrumb(`ritualAR:overlay-mount markers=${markers.length}`);
    return () => { crashLogger.breadcrumb('ritualAR:overlay-unmount'); };
  }, []);

  if (!userPos || !arkitOriginRef.current) return null;

  return (
    <View style={StyleSheet.absoluteFillObject} pointerEvents="box-none">
      <ViroARSceneNavigator
        autofocus
        worldAlignment="GravityAndHeading"
        provider="none"
        hdrEnabled
        bloomEnabled
        initialScene={{ scene: RitualARScene as any }}
        viroAppProps={{
          arkitOrigin: arkitOriginRef.current,
          markers,
          onCairnPress,
        }}
        style={StyleSheet.absoluteFillObject}
      />
    </View>
  );
}
