/**
 * ViroARRitualOverlay — Death-Stranding-style ritual circle AR rendering.
 *
 * Independent from ViroAROverlay (the production v122 sphere/icon renderer).
 * Both files share the SAME GPS anchoring + ARKit tracking primitives but
 * differ in visual presentation:
 *   - ViroAROverlay     → 3D sphere with PBR icon geometry (current production)
 *   - ViroARRitualOverlay → ground-plane ritual circle + chiral strands +
 *                           distance-triggered debris (this file, experimental)
 *
 * Toggle between them via ARScreen mode switch. This file does NOT modify
 * any production rendering; if abandoned, simply delete and remove the
 * import from ARScreen.
 *
 * Milestone 1: ground ritual circle only (no strands, no debris yet).
 */
import React, { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import {
  ViroARScene,
  ViroARSceneNavigator,
  ViroQuad,
  ViroBox,
  ViroPolyline,
  ViroParticleEmitter,
  Viro3DObject,
  ViroNode,
  ViroAmbientLight,
  ViroDirectionalLight,
  ViroMaterials,
  ViroAnimations,
  ViroTrackingStateConstants,
  type ViroTrackingState,
  type ViroTrackingReason,
} from '@reactvision/react-viro';
import type { Marker } from '../store/useMarkerStore';
import { useMarkerStore } from '../store/useMarkerStore';
import { crashLogger } from '../services/crashLogger';
import { API_BASE_URL } from '../config/api';

// ── Type → ritual circle texture mapping ──────────────────────
// Each PNG is a 1024×1024 transparent ring with type-coloured runes +
// centre icon. Generated by app/scripts/gen_ritual_circles.mjs.
const RITUAL_TEX = {
  danger:   require('../../assets/ar/ritual_circle_danger.png'),
  supply:   require('../../assets/ar/ritual_circle_supply.png'),
  junction: require('../../assets/ar/ritual_circle_junction.png'),
  scenic:   require('../../assets/ar/ritual_circle_scenic.png'),
  cairn:    require('../../assets/ar/ritual_circle_cairn.png'),
} as const;

// v150 sprite assets (5-way A/B test)
const STREAK_SPRITE = require('../../assets/ar/sprite_streak.png');
const DOT_SPRITE = require('../../assets/ar/sprite_dot.png');
const FLOW_GRADIENT = require('../../assets/ar/flow_gradient.png');

// Strand assets — 5 curves × 5 types = 25 GLBs. v143: colour is BAKED into
// the GLB's pbrMetallicRoughness.baseColorFactor at build time because
// Viro3DObject silently ignores the `materials` prop on iOS (verified via
// debug snapshots in v142 — strands rendered pure white with red material
// registered). Generated by app/scripts/gen_strand_glb.mjs.
const STRAND_GLBS: Record<string, any[]> = {
  danger: [
    require('../../assets/ar/strand_a_danger.glb'),
    require('../../assets/ar/strand_b_danger.glb'),
    require('../../assets/ar/strand_c_danger.glb'),
    require('../../assets/ar/strand_d_danger.glb'),
    require('../../assets/ar/strand_e_danger.glb'),
  ],
  supply: [
    require('../../assets/ar/strand_a_supply.glb'),
    require('../../assets/ar/strand_b_supply.glb'),
    require('../../assets/ar/strand_c_supply.glb'),
    require('../../assets/ar/strand_d_supply.glb'),
    require('../../assets/ar/strand_e_supply.glb'),
  ],
  junction: [
    require('../../assets/ar/strand_a_junction.glb'),
    require('../../assets/ar/strand_b_junction.glb'),
    require('../../assets/ar/strand_c_junction.glb'),
    require('../../assets/ar/strand_d_junction.glb'),
    require('../../assets/ar/strand_e_junction.glb'),
  ],
  scenic: [
    require('../../assets/ar/strand_a_scenic.glb'),
    require('../../assets/ar/strand_b_scenic.glb'),
    require('../../assets/ar/strand_c_scenic.glb'),
    require('../../assets/ar/strand_d_scenic.glb'),
    require('../../assets/ar/strand_e_scenic.glb'),
  ],
  cairn: [
    require('../../assets/ar/strand_a_cairn.glb'),
    require('../../assets/ar/strand_b_cairn.glb'),
    require('../../assets/ar/strand_c_cairn.glb'),
    require('../../assets/ar/strand_d_cairn.glb'),
    require('../../assets/ar/strand_e_cairn.glb'),
  ],
};
const STRAND_FLOW_TEX = require('../../assets/ar/strand_flow.png');

// v149: reduce strand count to 3 (was 5) — density was the dominant
// 'too chaotic' complaint. Three 120°-spaced offsets give a pleasing
// triangle arrangement without crowding.
const STRAND_OFFSETS = [
  { x: Math.cos(0.0 * Math.PI * 2 + 0.10), z: Math.sin(0.0 * Math.PI * 2 + 0.10) },
  { x: Math.cos((1/3) * Math.PI * 2 - 0.05), z: Math.sin((1/3) * Math.PI * 2 - 0.05) },
  { x: Math.cos((2/3) * Math.PI * 2 + 0.08), z: Math.sin((2/3) * Math.PI * 2 + 0.08) },
];

// 3 strand spin animation names
const STRAND_SWAY_ANIMS = ['strandSway0', 'strandSway1', 'strandSway2'];

// Strand visual constants. v2: GLB regenerated with 8m height (was 40m) and
// 0.04m base radius (was 0.18m) — see scripts/gen_strand_glb.mjs.
const STRAND_HEIGHT_M = 8;
const STRAND_BASE_SCALE = 1.0;

// Type aliases — same normalisation as ViroAROverlay so old DB rows keep working
const TYPE_REMAP: Record<string, keyof typeof RITUAL_TEX> = {
  water: 'supply',
  free:  'cairn',
  hut:   'cairn',
};
function normalizeType(t: string): keyof typeof RITUAL_TEX {
  if (t in RITUAL_TEX) return t as keyof typeof RITUAL_TEX;
  return TYPE_REMAP[t] ?? 'cairn';
}

// ── Constants ──────────────────────────────────────────────────
// Eye-level offset: place ritual centre slightly below ARKit camera Y so
// user looks down at it (same logic as ViroAROverlay v68 — GPS altitude is
// unreliable, anchor relative to camera height instead).
const RITUAL_GROUND_OFFSET_M = -1.2;
// Visibility range — beyond this, ritual circle is hidden (edge arrows
// take over, same threshold as production overlay).
const VISIBLE_RANGE_M = 50;
const NEAR_THRESHOLD_M = 10;
// Ritual circle physical size. v7 (post-v148 user feedback "5/100"):
// 0.6m → 0.3m. The smaller the disc the more the strands carry the
// visual weight. User explicitly mentioned the disc 'follows them'
// (likely visual parallax illusion at 0.6m radius).
const RITUAL_BASE_SIZE_M = 0.3;
// Stable tracking settle window (ms). ARKit briefly reports TRACKING_NORMAL
// during relocalisation while the world transform is still being corrected.
// Production ViroAROverlay uses 1500ms to prevent the "flag flies into the
// sky" bug, but the ritual circle is anchored to the ground (y is constant)
// so a brief world-frame transient is much less visually catastrophic.
// Shorter settle = faster recovery after putting the phone down + picking
// it up (a common interaction the user explicitly flagged in M1 testing).
const TRACKING_SETTLE_MS = 400;

// ── GPS → ARKit world coords ──────────────────────────────────
// Identical math to ViroAROverlay.gpsToArWorld but inlined to keep this
// file self-contained.
function gpsToArWorld(
  origin: { lat: number; lng: number; alt?: number | null },
  target: { lat: number; lng: number; alt?: number | null },
): [number, number, number] {
  const dLat = target.lat - origin.lat;
  const dLng = target.lng - origin.lng;
  const cosLat = Math.cos((origin.lat * Math.PI) / 180);
  const northM = dLat * 111000;
  const eastM = dLng * 111000 * cosLat;
  return [eastM, RITUAL_GROUND_OFFSET_M, -northM];
}

interface CairnWorldPos {
  id: string;
  type: string;
  x: number; y: number; z: number;
  dist: number;
}

interface Props {
  markers: Marker[];
  userPos: { lat: number; lng: number; alt?: number | null } | null;
  userHeading: number | null;
  onStatus?: (status: { glReady: boolean; cairnCount: number }) => void;
  onCairnPress?: (markerId: string) => void;
  // v148: feed ARScreen the live ARKit camera frame so its plant flow
  // (hit-test in ARScreen.tsx:472-520) can land cairns where the user is
  // aiming. Without this prop, ARScreen falls back to last-known cam state
  // from production overlay, planting where the cursor was BEFORE switching
  // to ritual mode (= 'water marker appeared on the right when I aimed
  // left' bug).
  onArFrame?: (info: {
    camera: { position: [number, number, number]; forward: [number, number, number] };
    cairns: CairnWorldPos[];
    origin: { lat: number; lng: number; alt: number | null } | null;
    groundY: number | null;
  }) => void;
}

// ─────────────────────────────────────────────────────────────────
// AR scene (inner — accesses viroAppProps via polling, same pattern as
// ViroAROverlay because viroAppProps is mutated in-place not via React state).
// ─────────────────────────────────────────────────────────────────
function RitualARScene(props: any) {
  const [liveProps, setLiveProps] = useState<{
    arkitOrigin: { lat: number; lng: number; alt?: number | null } | null;
    markers: Marker[];
    onCairnPress?: (id: string) => void;
    onArFrame?: Props['onArFrame'];
  }>(() => {
    const p = props.sceneNavigator?.viroAppProps ?? {};
    return {
      arkitOrigin: p.arkitOrigin ?? null,
      markers: p.markers ?? [],
      onCairnPress: p.onCairnPress,
      onArFrame: p.onArFrame,
    };
  });

  useEffect(() => {
    const id = setInterval(() => {
      const p = props.sceneNavigator?.viroAppProps ?? {};
      setLiveProps(prev => {
        const nextMarkers: Marker[] = p.markers ?? [];
        if (
          prev.arkitOrigin === p.arkitOrigin &&
          prev.markers.length === nextMarkers.length &&
          prev.onCairnPress === p.onCairnPress &&
          prev.onArFrame === p.onArFrame
        ) return prev;
        return {
          arkitOrigin: p.arkitOrigin ?? null,
          markers: nextMarkers,
          onCairnPress: p.onCairnPress,
          onArFrame: p.onArFrame,
        };
      });
    }, 500);
    return () => clearInterval(id);
  }, []);

  const { arkitOrigin, markers, onCairnPress, onArFrame } = liveProps;
  const [tracking, setTracking] = useState(false);
  const [stableTracking, setStableTracking] = useState(false);
  const [materialsReady, setMaterialsReady] = useState(false);

  // v146: full GPS anchoring + ground-plane logic copy-pasted from
  // ViroAROverlay.tsx (production v122). The earlier simplified version
  // ignored ARKit plane detection AND camera-Y drift correction, which
  // is why the user saw "markers always 1m in front of me" + "all
  // markers piled together at one spot". Both are bugs we already
  // solved on the production side via groundYRef + handleAnchor +
  // onCameraTransformUpdate. This is a 1:1 port — DO NOT simplify.
  const cairnNodesRef = useRef<CairnWorldPos[]>([]);
  const groundYRef = useRef<number | null>(null);
  // v150: Lock the ground Y at FIRST detection per session. Once a marker is
  // placed it must never visually translate vertically — even if ARKit later
  // refines the floor estimate. The "marker follows me" bug in v148/149 was
  // caused by groundYRef updating during normal use, which re-ran the cairnY
  // computation in the useMemo and shifted every marker's y by 0.05-0.4m.
  // Hold the first stable ground value forever per AR session.
  const lockedGroundYRef = useRef<number | null>(null);
  const [groundYTick, setGroundYTick] = useState(0);
  const camForwardRef = useRef<number[]>([0, 0, -1]);
  const camYRef = useRef<number>(1.5);
  const lastCairnYRef = useRef<number | null>(null);
  const lastFrameTsRef = useRef(0);

  // ── Register materials + animations (deferred to mount, RN-safe) ──
  useEffect(() => {
    try {
      const types = ['danger', 'supply', 'junction', 'scenic', 'cairn'] as const;
      // Per-type colour for strand tinting. v3 (post-v134 feedback): users
      // report strands still appear white. Diagnostic: use saturated primary
      // colours so we can verify if material assignment is working at all.
      // If strands STILL look white in v135 → material isn't being applied
      // (likely GLB ships without material reference, Viro defaults to white).
      // If strands turn coloured → just need to dim further.
      const STRAND_TINT: Record<string, string> = {
        danger:   '#ff0000',  // pure red — diagnostic
        supply:   '#00ff00',  // pure green
        junction: '#ff8800',  // orange
        scenic:   '#0044ff',  // pure blue
        cairn:    '#ffaa00',  // amber gold
      };
      const mats: Record<string, any> = {};
      for (const t of types) {
        // Ritual ground circle (unchanged from M1)
        mats[`ritual${t}`] = {
          lightingModel: 'Constant',
          diffuseTexture: RITUAL_TEX[t],
          blendMode: 'Add',
          writesToDepthBuffer: false,
          readsFromDepthBuffer: true,
        };
        // Strand material — one per type. v4 (post-v135 diagnostic): logs
        // confirmed strands ARE loading (ritualAR:strand-loaded × 5) but
        // user sees nothing. Two suspects:
        //   1. v135 Alpha blend × low-alpha texture = invisible
        //   2. GLB radius 0.04m × Alpha = nearly transparent thin wisp
        // v4 fix: drop the texture entirely, use solid colour material.
        // If v136 strands appear → texture alpha was the problem.
        // If still invisible → GLB is too thin to see at 1m, regenerate
        //   thicker.
        const cap = t.charAt(0).toUpperCase() + t.slice(1);
        mats[`strand${cap}`] = {
          lightingModel: 'Constant',
          diffuseColor: STRAND_TINT[t],
          // No diffuseTexture, no blendMode — solid opaque tube.
          writesToDepthBuffer: true,
          readsFromDepthBuffer: true,
        };
        // v147 BISECTION: box material — control case for animation test.
        mats[`box${t}`] = {
          lightingModel: 'Constant',
          diffuseColor: STRAND_TINT[t],
        };
      }
      // v150 NEW: scenic shader — UV-scroll flow over time, fresnel rim,
      // tip fade. Recipe A from docs/viro-knowledge.md. JS pushes 'time'
      // uniform every 32ms via ViroMaterials.updateShaderUniform.
      mats['scenicFlow'] = {
        lightingModel: 'Constant',
        blendMode: 'Add',
        bloomThreshold: 0.1,
        diffuseColor: '#7090ff',
        diffuseTexture: FLOW_GRADIENT,
        wrapT: 'Repeat',
        shaderModifiers: {
          surface: {
            uniforms: 'uniform highp float time;',
            body: `
              highp vec2 uv = vec2(_surface.diffuse_texcoord.x,
                                    _surface.diffuse_texcoord.y - time * 0.0008);
              highp float bandAlpha = texture(diffuseTexture, fract(uv)).a;
              highp float tipFade = 1.0 - smoothstep(0.5, 1.0, _surface.diffuse_texcoord.y);
              _surface.diffuse_color.a = bandAlpha * tipFade;
            `,
          } as any,
        },
        materialUniforms: [
          { name: 'time', type: 'float', value: 0 },
        ],
      } as any;
      // v150 NEW: cairn layered ribbon materials (3 stacked billboard quads).
      mats['cairnLayer1'] = {
        lightingModel: 'Constant',
        blendMode: 'Add',
        diffuseColor: '#80602a',
        diffuseTexture: FLOW_GRADIENT,
        bloomThreshold: 0.15,
      };
      mats['cairnLayer2'] = {
        lightingModel: 'Constant',
        blendMode: 'Add',
        diffuseColor: '#d4a050',
        diffuseTexture: FLOW_GRADIENT,
        bloomThreshold: 0.10,
      };
      mats['cairnLayer3'] = {
        lightingModel: 'Constant',
        blendMode: 'Add',
        diffuseColor: '#ffe0a0',
        diffuseTexture: FLOW_GRADIENT,
        bloomThreshold: 0.05,
      };
      ViroMaterials.createMaterials(mats);

      // Animations: slow rotation around Y for the ground ring + 5 small
      // independent sway animations for the strand wrappers. Each strandSway
      // is a single non-chained relative rotation looped — small enough that
      // looping `+=N` doesn't visually drift (delta accumulates but the
      // rotation is so small the user perceives it as gentle oscillation
      // averaged across the cycle).
      // v148: chained sway animation. Source-verified syntax from
      // ViroAnimations.ts:46 — `ViroAnimationDict[key]` accepts
      // `ViroRegisterableAnimation | ViroRegisterableAnimation[]`. Array
      // form = inline chain (Viro plays elements in order, then loops).
      // This is the PROPER way; v147 single-segment loop was useless
      // because absolute-value loops snap-reset on each cycle.
      // Chain: 0° → +deg → 0° → -deg → 0° gives true oscillation around
      // vertical without drift. EaseInEaseOut for natural-feeling sway.
      const chain = (axis: 'rotateZ' | 'rotateX', deg: number, segMs: number): any[] => [
        { properties: { [axis]:  deg }, duration: segMs, easing: 'EaseInEaseOut' },
        { properties: { [axis]:    0 }, duration: segMs, easing: 'EaseInEaseOut' },
        { properties: { [axis]: -deg }, duration: segMs, easing: 'EaseInEaseOut' },
        { properties: { [axis]:    0 }, duration: segMs, easing: 'EaseInEaseOut' },
      ];

      ViroAnimations.registerAnimations({
        ringSpinSlow: {
          properties: { rotateY: '+=360' },
          duration: 60000,
          easing: 'Linear',
        },
        strandSway0: chain('rotateZ',  6, 1900),
        strandSway1: chain('rotateX',  7, 2200),
        strandSway2: chain('rotateZ',  5, 2500),
      });
      crashLogger.breadcrumb('ritualAR:animations-registered v149 [3 strands chained sway]');

      setMaterialsReady(true);
      crashLogger.breadcrumb('ritualAR:materials-registered');
    } catch (e: any) {
      crashLogger.breadcrumb(`ritualAR:material-error ${e?.message ?? e}`);
    }
  }, []);

  // ── Tracking state ─────────────────────────────────────────────
  const onTrackingUpdated = useCallback((state: ViroTrackingState, _reason: ViroTrackingReason) => {
    const ok = state === ViroTrackingStateConstants.TRACKING_NORMAL;
    setTracking(ok);
    crashLogger.breadcrumb(`ritualAR:tracking state=${state}`);
  }, []);

  useEffect(() => {
    if (!tracking) {
      setStableTracking(false);
      return;
    }
    const id = setTimeout(() => setStableTracking(true), TRACKING_SETTLE_MS);
    return () => clearTimeout(id);
  }, [tracking]);

  // ── World position computation (v150: locked ground Y to prevent drift) ──
  const cairnNodes = useMemo<CairnWorldPos[]>(() => {
    if (!arkitOrigin) return [];
    const FALLBACK_HOLD_HEIGHT_M = 1.4;
    // v150: once we have any ground reading, freeze it. Re-detection after that
    // does NOT shift markers. This is what fixes the 'circles follow me' bug —
    // markers' y was changing by 0.05-0.4m each ground refinement.
    if (lockedGroundYRef.current === null && groundYRef.current !== null) {
      lockedGroundYRef.current = groundYRef.current;
      crashLogger.breadcrumb(
        `ritualAR:ground-LOCKED y=${lockedGroundYRef.current.toFixed(3)} (frozen for session)`
      );
    }
    const ground = lockedGroundYRef.current;  // ← use locked value, not live
    const nodes: CairnWorldPos[] = [];
    for (const m of markers) {
      const [x, _y, z] = gpsToArWorld(arkitOrigin, m as any);
      const horizontal = Math.hypot(x, z);
      if (horizontal > VISIBLE_RANGE_M) continue;
      // y is permanent: locked ground if known, else hand-held fallback.
      // No matter how many planes ARKit refines later, this never changes.
      const y = ground !== null ? ground : -FALLBACK_HOLD_HEIGHT_M;
      crashLogger.breadcrumb(
        `ritualAR:cairn-pos id=${m.id.slice(-4)} type=${m.type} ` +
        `xyz=(${x.toFixed(2)},${y.toFixed(2)},${z.toFixed(2)}) ` +
        `dist=${horizontal.toFixed(1)}m lockedGround=${ground === null ? 'null' : ground.toFixed(2)}`,
      );
      nodes.push({ id: m.id, type: m.type as string, x, y, z, dist: horizontal });
    }
    cairnNodesRef.current = nodes;
    crashLogger.breadcrumb(
      `ritualAR:scene:nodes total=${markers.length} visible=${nodes.length} ` +
      `range=${VISIBLE_RANGE_M}m lockedGround=${ground === null ? 'null' : ground.toFixed(2)}`,
    );
    return nodes;
  }, [markers, arkitOrigin?.lat, arkitOrigin?.lng, arkitOrigin?.alt, groundYTick]);

  // Camera transform — drift correction (1:1 from ViroAROverlay v119) +
  // v148 onArFrame fan-out so ARScreen's plant-flow hit-test sees the
  // current ritual-mode camera state. Without this fan-out, plant uses
  // sphere-mode's stale camera vector → markers land at wrong xyz.
  const onCameraTransformUpdate = useCallback((evt: any) => {
    const now = Date.now();
    if (now - lastFrameTsRef.current < 100) return; // 10Hz throttle
    lastFrameTsRef.current = now;
    const t = evt?.cameraTransform;
    if (!t || !t.position || !t.forward) return;
    camForwardRef.current = t.forward;
    const camY = t.position[1];
    if (typeof camY === 'number' && isFinite(camY)) {
      camYRef.current = camY;
      const cur = groundYRef.current;
      if (cur !== null) {
        const expectedFloor = camY - 1.5;
        const deviation = Math.abs(cur - expectedFloor);
        if (deviation > 0.7) {
          crashLogger.breadcrumb(
            `ritualAR:ground-stale camY=${camY.toFixed(2)} expectedFloor=${expectedFloor.toFixed(2)} cachedGround=${cur.toFixed(2)} dev=${deviation.toFixed(2)}m`
          );
          groundYRef.current = null;
          setGroundYTick((n) => n + 1);
        }
      }
    }
    if (onArFrame) {
      onArFrame({
        camera: { position: t.position, forward: t.forward },
        cairns: cairnNodesRef.current,
        origin: arkitOrigin ? { lat: arkitOrigin.lat, lng: arkitOrigin.lng, alt: arkitOrigin.alt ?? null } : null,
        groundY: groundYRef.current,
      });
    }
  }, [onArFrame, arkitOrigin]);

  // Anchor handler — ground-plane detection (1:1 from ViroAROverlay v119)
  const handleAnchor = useCallback((anchor: any) => {
    if (!anchor) return;
    if (anchor.type !== 'plane') return;
    if (anchor.alignment && anchor.alignment !== 'Horizontal' && anchor.alignment !== 'horizontal') return;
    const y = anchor.position?.[1];
    if (typeof y !== 'number' || !isFinite(y)) return;
    if (y > -0.5) return; // ceiling reject
    const expectedFloor = camYRef.current - 1.5;
    const planeDeviation = Math.abs(y - expectedFloor);
    if (planeDeviation > 0.7) return; // desk/table reject
    const cur = groundYRef.current;
    const STABILITY_THRESHOLD_M = 0.10;
    if (cur === null) {
      const fwd = camForwardRef.current;
      if (fwd[1] > 0.7) {
        crashLogger.breadcrumb(`ritualAR:plane:first-skip y=${y.toFixed(3)} fwd1=${fwd[1].toFixed(2)} (phone flat)`);
        return;
      }
      groundYRef.current = y;
      setGroundYTick((n) => n + 1);
      crashLogger.breadcrumb(
        `ritualAR:plane:first y=${y.toFixed(3)} camY=${camYRef.current.toFixed(2)} expectedFloor=${expectedFloor.toFixed(2)}`
      );
    } else if (y < cur - STABILITY_THRESHOLD_M) {
      crashLogger.breadcrumb(`ritualAR:plane:lower y=${y.toFixed(3)} prev=${cur.toFixed(3)} delta=${(y - cur).toFixed(3)}`);
      groundYRef.current = y;
      setGroundYTick((n) => n + 1);
    }
  }, []);
  const onAnchorFound = useCallback((anchor: any) => handleAnchor(anchor), [handleAnchor]);
  const onAnchorUpdated = useCallback((anchor: any) => handleAnchor(anchor), [handleAnchor]);

  return (
    <ViroARScene
      onTrackingUpdated={onTrackingUpdated}
      onCameraTransformUpdate={onCameraTransformUpdate}
      onAnchorFound={onAnchorFound}
      onAnchorUpdated={onAnchorUpdated}
    >
      <ViroAmbientLight color="#ffffff" intensity={300} />
      <ViroDirectionalLight color="#ffffff" direction={[0.0, -1.0, -0.5]} intensity={500} />

      {materialsReady && stableTracking && cairnNodes.map((c) => (
        <RitualInstance
          key={c.id}
          id={c.id}
          type={c.type}
          x={c.x}
          y={c.y}
          z={c.z}
          dist={c.dist}
          onPress={onCairnPress}
        />
      ))}
    </ViroARScene>
  );
}

// ─────────────────────────────────────────────────────────────────
// RitualInstance — one marker rendered as ground ritual circle.
// M1 scope: just the circle. Strands + label + debris will be added
// in M2/M3/M4.
// ─────────────────────────────────────────────────────────────────
function RitualInstance(props: {
  id: string;
  type: string;
  x: number; y: number; z: number;
  dist: number;
  onPress?: (id: string) => void;
}) {
  const { id, type, x, y, z, dist, onPress } = props;
  const normalized = normalizeType(type);
  const matName = `ritual${normalized}`;

  // Distance-aware scale: at 0–10m show natural size, fade larger toward
  // 50m so it remains visible from afar without being huge up close.
  let sizeMul: number;
  if (dist <= NEAR_THRESHOLD_M) {
    sizeMul = 1.0;
  } else {
    const t = Math.min(1, (dist - NEAR_THRESHOLD_M) / (VISIBLE_RANGE_M - NEAR_THRESHOLD_M));
    sizeMul = 1.0 + t * 1.5;     // grows to 2.5x at edge of visibility
  }
  const size = RITUAL_BASE_SIZE_M * sizeMul;

  const onPressCb = useCallback(() => {
    crashLogger.breadcrumb(`ritualAR:press id=${id.slice(-6)}`);
    onPress?.(id);
  }, [id, onPress]);

  useEffect(() => {
    const cap = normalized.charAt(0).toUpperCase() + normalized.slice(1);
    crashLogger.breadcrumb(
      `ritualAR:render id=${id.slice(-6)} type=${type} norm=${normalized} dist=${dist.toFixed(1)} size=${size.toFixed(2)} strandMat=strand${cap}`,
    );
  }, [id, type, normalized, dist, size]);

  return (
    <ViroNode position={[x, y, z]} onClick={onPressCb}>
      {/* Outer wrapper handles the slow rotation. Inner quad lies flat on
          the ground (rotation X = -90°). The quad uses Add blend so the
          ring glows additively on top of the camera feed. */}
      <ViroNode
        animation={{ name: 'ringSpinSlow', run: true, loop: true }}
      >
        <ViroQuad
          rotation={[-90, 0, 0]}                // lay flat on ground
          width={size}
          height={size}
          materials={[matName]}
        />
      </ViroNode>

      {/* Chiral strands — 5 GLB ribbon meshes rising from points around the
          ring. Each is a curved S-tube ~40m tall with along-length thickness
          variation baked into the geometry. Materials use Constant lighting
          + Add blend + per-type diffuseColor tint so all 5 strands draw
          from a single neutral white flow texture.
          The strand_a..e.glb meshes have distinct curve shapes; combined with
          per-strand yaw (i * 17°) and per-strand sway animations, no two
          strands look alike.
          Step 4 will add a UV-scroll shaderModifier so the texture appears
          to flow upward inside each strand (DS chiral effect). */}
      {/* v150: 5 type 5 distinct visual experiments. Each marker type plays
          a different strand technique so we can A/B compare in real AR.
          See docs/viro-knowledge.md for the canonical recipes.
            danger    = streak particles (discrete rising fragments)
            supply    = dot particles (sparse floating glow)
            junction  = static GLB (varying thickness, colour-baked)
            scenic    = ViroPolyline + flow shader (UV scroll)
            cairn     = stacked billboard quads (multi-layer transparent ribbons)
          Future v151 will pick the winner. */}
      <StrandsForType type={normalized} ringRadius={RITUAL_BASE_SIZE_M * 0.5} />
    </ViroNode>
  );
}

// ─────────────────────────────────────────────────────────────────
// StrandsForType — v150 5-way A/B test renderer
// ─────────────────────────────────────────────────────────────────
function StrandsForType({ type, ringRadius }: { type: string; ringRadius: number }) {
  // 3 anchor points 120° apart for all variants
  const offsets = useMemo(() => [0, 1, 2].map(i => {
    const a = (i / 3) * Math.PI * 2 + 0.1;
    return { x: Math.cos(a) * ringRadius, z: Math.sin(a) * ringRadius };
  }), [ringRadius]);

  // Drive scenic shader time uniform from JS (canonical Viro pattern,
  // confirmed in ViroMaterials.ts:211 and docs).
  useEffect(() => {
    if (type !== 'scenic') return;
    const start = Date.now();
    const id = setInterval(() => {
      try {
        (ViroMaterials as any).updateShaderUniform?.(
          'scenicFlow', 'time', 'float', Date.now() - start,
        );
      } catch (e: any) {
        // older Viro builds don't have updateShaderUniform — silently skip
      }
    }, 32);  // 30Hz is enough for visual flow
    return () => clearInterval(id);
  }, [type]);

  if (type === 'danger') {
    // ─── DANGER: discrete rising streaks (粒子断续上升) ───
    return (
      <>
        {offsets.map((off, i) => (
          <ViroParticleEmitter
            key={`danger-${i}`}
            position={[off.x, 0.05, off.z]}
            duration={3000}
            delay={i * 350}
            run={true}
            loop
            fixedToEmitter
            image={{
              source: STREAK_SPRITE,
              height: 0.40, width: 0.06,
              bloomThreshold: 0.05,
            }}
            spawnBehavior={{
              particleLifetime: [1500, 3500],   // wide range = irregular
              maxParticles: 8,
              emissionRatePerSecond: [3, 5],
              spawnVolume: { shape: 'sphere', params: [0.05] },
            }}
            particleAppearance={{
              opacity: {
                initialRange: [0, 0],
                factor: 'Time',
                interpolation: [
                  { interval: [0, 300],   endValue: 0.95 },
                  { interval: [300, 2400], endValue: 0.95 },
                  { interval: [2400, 3500], endValue: 0 },
                ],
              },
              scale: {
                initialRange: [[0.8, 0.8, 0.8], [1.2, 1.2, 1.2]],
                factor: 'Time',
                interpolation: [
                  { interval: [0, 1500],   endValue: [1.0, 1.4, 1.0] },
                  { interval: [1500, 3500], endValue: [0.4, 0.8, 0.4] },
                ],
              },
              color: {
                initialRange: ['#ff6a55', '#ffaa66'],
                factor: 'Time',
                interpolation: [],
              },
            }}
            particlePhysics={{
              velocity: { initialRange: [[-0.04, 1.0, -0.04], [0.04, 1.6, 0.04]] },
              acceleration: { initialRange: [[0, 0.05, 0], [0, 0.10, 0]] },
            }}
          />
        ))}
      </>
    );
  }

  if (type === 'supply' || type === 'water') {
    // ─── SUPPLY: sparse floating dots (稀疏漂浮光点) ───
    return (
      <>
        {offsets.map((off, i) => (
          <ViroParticleEmitter
            key={`supply-${i}`}
            position={[off.x, 0.05, off.z]}
            duration={4000}
            delay={i * 500}
            run={true}
            loop
            fixedToEmitter
            image={{
              source: DOT_SPRITE,
              height: 0.12, width: 0.12,
              bloomThreshold: 0.05,
            }}
            spawnBehavior={{
              particleLifetime: [3000, 5000],   // longer life = drifty
              maxParticles: 6,
              emissionRatePerSecond: [1.5, 2.5],
              spawnVolume: { shape: 'sphere', params: [0.08] },
            }}
            particleAppearance={{
              opacity: {
                initialRange: [0, 0],
                factor: 'Time',
                interpolation: [
                  { interval: [0, 600],   endValue: 0.85 },
                  { interval: [600, 3500], endValue: 0.85 },
                  { interval: [3500, 5000], endValue: 0 },
                ],
              },
              scale: {
                initialRange: [[0.6, 0.6, 0.6], [1.0, 1.0, 1.0]],
                factor: 'Time',
                interpolation: [
                  { interval: [0, 2500],   endValue: [1.4, 1.4, 1.4] },
                  { interval: [2500, 5000], endValue: [0.4, 0.4, 0.4] },
                ],
              },
              color: {
                initialRange: ['#5fcc7a', '#a0e8b0'],
                factor: 'Time',
                interpolation: [],
              },
            }}
            particlePhysics={{
              velocity: { initialRange: [[-0.05, 0.4, -0.05], [0.05, 0.8, 0.05]] },
              acceleration: { initialRange: [[0, 0, 0], [0, 0.05, 0]] },
            }}
          />
        ))}
      </>
    );
  }

  if (type === 'junction') {
    // ─── JUNCTION: static GLB tubes (现有 GLB,变薄变短) ───
    const glbForType = STRAND_GLBS.junction;
    return (
      <>
        {offsets.map((off, i) => (
          <ViroNode
            key={`junction-${i}`}
            position={[off.x, 0.0, off.z]}
            rotation={[0, i * 23, 0]}
          >
            <Viro3DObject
              source={glbForType[i]}
              type="GLB"
              scale={[1.0, 0.6, 1.0]}   // squish vertically — testing thickness
              onLoadEnd={() => crashLogger.breadcrumb(`ritualAR:junction-loaded i=${i}`)}
              onError={(e: any) => crashLogger.breadcrumb(`ritualAR:junction-fail i=${i}`)}
            />
          </ViroNode>
        ))}
      </>
    );
  }

  if (type === 'scenic' || type === 'free') {
    // ─── SCENIC: ViroPolyline + flow shader (流动光柱) ───
    // Polyline runs from ground (y=0) to tip (y=4m). Shader scrolls flow_gradient
    // texture along V over time uniform. This is the DS-aesthetic recipe from
    // docs/viro-knowledge.md Recipe A.
    return (
      <>
        {offsets.map((off, i) => (
          <ViroPolyline
            key={`scenic-${i}`}
            position={[off.x, 0.05, off.z]}
            points={[[0, 0, 0], [0, 4.0, 0]]}
            thickness={0.06}
            materials={['scenicFlow']}
          />
        ))}
      </>
    );
  }

  if (type === 'cairn' || type === 'hut') {
    // ─── CAIRN: stacked billboard ribbons (3 层透光带) ───
    // Three ViroQuads at slightly different sizes, all billboarded toward
    // camera, with Constant Add material. Layered transparency = soft glow column.
    return (
      <>
        {offsets.map((off, i) => (
          <ViroNode
            key={`cairn-${i}`}
            position={[off.x, 1.5, off.z]}
            transformBehaviors={['billboard']}
          >
            <ViroQuad width={0.10} height={3.0} materials={['cairnLayer1']} position={[0, 0, -0.01]} />
            <ViroQuad width={0.06} height={3.2} materials={['cairnLayer2']} position={[0, 0, 0]} />
            <ViroQuad width={0.02} height={3.4} materials={['cairnLayer3']} position={[0, 0, 0.01]} />
          </ViroNode>
        ))}
      </>
    );
  }

  return null;
}

// Public ref handle exposed to ARScreen for debugging.
export interface ViroARRitualOverlayHandle {
  /**
   * Take a screenshot of the Viro AR view + dump diagnostic state.
   * Image is base64-encoded and written to telemetry as a special
   * `debug-snapshot` breadcrumb. Backend pulls it via mysql; the
   * scripts/get_debug_snapshot.mjs helper decodes to PNG locally.
   */
  takeDebugSnapshot: () => Promise<{ success: boolean; error?: string }>;
}

// ─────────────────────────────────────────────────────────────────
// Public component — same Props shape as ViroAROverlay so ARScreen
// can swap them with a single ternary.
// ─────────────────────────────────────────────────────────────────
export const ViroARRitualOverlay = forwardRef<ViroARRitualOverlayHandle, Props>(function ViroARRitualOverlay({
  markers,
  userPos,
  userHeading: _userHeading,
  onStatus,
  onCairnPress,
  onArFrame,
}: Props, ref) {
  const arkitOriginRef = useRef<{ lat: number; lng: number; alt?: number | null } | null>(null);
  const viroNavRef = useRef<any>(null);
  const [originReady, setOriginReady] = useState(false);

  // Expose debug snapshot to parent (ARScreen). Captures the live Viro
  // render + emits diagnostic breadcrumbs with current strand state.
  useImperativeHandle(ref, () => ({
    takeDebugSnapshot: async () => {
      try {
        // ViroARSceneNavigator exposes its native methods on
        // `arSceneNavigator` (the class field), NOT on the component
        // instance directly. v138 used `viroNavRef.current.takeScreenshot`
        // and got 'no-viro-ref' because that method doesn't exist there.
        const nav = (viroNavRef.current as any)?.arSceneNavigator;
        const takeScreenshot = nav?.takeScreenshot;
        if (typeof takeScreenshot !== 'function') {
          const keys = viroNavRef.current ? Object.keys(viroNavRef.current).slice(0, 20).join(',') : 'null';
          const navKeys = nav ? Object.keys(nav).slice(0, 20).join(',') : 'null';
          crashLogger.breadcrumb(`ritualAR:debug-snapshot-no-fn refKeys=[${keys}] navKeys=[${navKeys}]`);
          return { success: false, error: 'takeScreenshot-not-fn' };
        }
        crashLogger.breadcrumb(`ritualAR:debug-snapshot-start markers=${markers.length}`);
        const result = await takeScreenshot('cairn-debug', false);
        crashLogger.breadcrumb(
          `ritualAR:debug-snapshot-result success=${result?.success} url=${result?.url ?? 'none'} err=${result?.errorCode ?? 'none'}`
        );
        if (result?.success && result?.url) {
          // Read png file via fetch on file:// URI → Blob (RN supports this).
          const fileUri = result.url.startsWith('file://') ? result.url : `file://${result.url}`;
          const resp = await fetch(fileUri);
          const blob = await resp.blob();
          const snapshotId = `snap-${Date.now()}`;
          crashLogger.breadcrumb(
            `ritualAR:debug-snapshot-meta id=${snapshotId} bytes=${blob.size} markers=${markers.length}`
          );
          // v142: backend now has /api/debug-snapshot — POST raw PNG
          // bytes directly. No base64, no chunking, no telemetry pollution.
          // 10× simpler + faster than v141's JSONL chunking approach.
          const ts = Date.now();
          const snapMeta = {
            markers: markers.length,
            ts,
          };
          try {
            const metaB64 = global.btoa
              ? global.btoa(JSON.stringify(snapMeta))
              : (require('buffer') as any).Buffer.from(JSON.stringify(snapMeta)).toString('base64');
            const url = `${API_BASE_URL.replace(/\/$/, '')}/api/debug-snapshot`
              + `?id=${encodeURIComponent(snapshotId)}`
              + `&meta=${encodeURIComponent(metaB64)}`;
            const resp = await fetch(url, {
              method: 'POST',
              headers: {
                'Content-Type': 'image/png',
                'X-Cairn-Device-Os': 'ios',
                'X-Cairn-App-Version': '0.2.0',
                'X-Cairn-Ar-Mode': 'ritual',
              },
              body: blob,
            });
            const status = resp.status;
            const respText = await resp.text().catch(() => '');
            crashLogger.breadcrumb(`ritualAR:debug-snapshot-uploaded sid=${snapshotId} status=${status} bytes=${blob.size} resp=${respText.slice(0, 100)}`);
            if (status >= 200 && status < 300) {
              return { success: true, error: `OK ${status} sid=${snapshotId} bytes=${blob.size}` };
            }
            return { success: false, error: `http ${status}: ${respText.slice(0, 100)}` };
          } catch (e: any) {
            return { success: false, error: `fetch-fail: ${e?.message ?? e}` };
          }
        }
        return { success: false, error: result?.errorCode ?? 'no-url' };
      } catch (e: any) {
        crashLogger.breadcrumb(`ritualAR:debug-snapshot-error ${e?.message ?? e}`);
        return { success: false, error: String(e?.message ?? e) };
      }
    },
  }), [markers.length]);

  // Reuse the SAME persisted origin as ViroAROverlay so switching modes
  // doesn't move the markers (both renderers share the world frame).
  const persistedArOrigin = useMarkerStore(s => s.arOrigin);
  const setArOriginIfMissing = useMarkerStore(s => s.setArOriginIfMissing);

  useEffect(() => {
    if (persistedArOrigin) {
      arkitOriginRef.current = { ...persistedArOrigin };
      setOriginReady(true);
      crashLogger.breadcrumb(
        `ritualAR:origin-restored lat=${persistedArOrigin.lat.toFixed(6)} lng=${persistedArOrigin.lng.toFixed(6)}`,
      );
    } else {
      arkitOriginRef.current = null;
      setOriginReady(false);
      crashLogger.breadcrumb('ritualAR:origin-reset');
    }
    return () => { crashLogger.breadcrumb('ritualAR:session-ended'); };
  }, []);

  useEffect(() => {
    if (!arkitOriginRef.current && userPos) {
      const o = { lat: userPos.lat, lng: userPos.lng, alt: userPos.alt ?? null };
      arkitOriginRef.current = o;
      setOriginReady(true);
      setArOriginIfMissing(o);
      crashLogger.breadcrumb(
        `ritualAR:origin-set lat=${userPos.lat.toFixed(6)} lng=${userPos.lng.toFixed(6)}`,
      );
    }
  }, [userPos?.lat, userPos?.lng, userPos?.alt]);

  useEffect(() => {
    if (onStatus) onStatus({ glReady: originReady, cairnCount: markers.length });
  }, [markers.length, onStatus, originReady]);

  useEffect(() => {
    crashLogger.breadcrumb(`ritualAR:overlay-mount markers=${markers.length}`);
    return () => { crashLogger.breadcrumb('ritualAR:overlay-unmount'); };
  }, []);

  if (!userPos || !arkitOriginRef.current) return null;

  return (
    <View style={StyleSheet.absoluteFillObject} pointerEvents="box-none">
      <ViroARSceneNavigator
        ref={viroNavRef}
        autofocus
        worldAlignment="GravityAndHeading"
        provider="none"
        hdrEnabled
        bloomEnabled
        initialScene={{ scene: RitualARScene as any }}
        viroAppProps={{
          arkitOrigin: arkitOriginRef.current,
          markers,
          onCairnPress,
          onArFrame,
        }}
        style={StyleSheet.absoluteFillObject}
      />
    </View>
  );
});
